library(geosphere)
library(htmltools)
library(leaflet)
library(data.table)
library(plotGoogleMaps)
library(reshape)
library(shiny)
# print('hey there')
loc_data <- data.table(readRDS('data/All_data_app.Rds'))
e_dt <- read.csv('data/Entities_mapping.csv', stringsAsFactors = F)
